### ISSUE TITLE
General questions on worker design

### ISSUE THREAD

**Issue by wilsonwang371** [ray-project/ray_beam_runner#8]
As we discussed previously, I want to discuss a little bit about how we implement worker on ray. In FnAPIRunner implementation, workers have a few design detail questions.
- input/output using a centralized manager buffer. How do we implement them in ray? Do we need to use actors? because ray saved objects are immutable. To be able to update data, we may need to use actors.
- state management is done through a StateServicer. What changes do we need to implement it on Ray? Will actors pattern be good enough for a state management in beam on ray?
- SDKHarness is a wrapper around SDKWorker, I am thinking probably we only need to implement SDKWorker and no need to implement SDKHarness. 
- To improve the performance, we may need to change the design after a certain point. Since current implementation of FnAPIRunner has a bottleneck in the central manager which serially run and communicate with each of the stage bundles.

If needed, we can later hold meetings to talk some of the details.

**Comment by pabloem** [comment]
the current implementation relies on the SDK worker interface, but we may even be able to skip that interface, and use the internal interfaces for it.
